apiVersion: kalypso.kalypso.io/v1alpha1
kind: ClusterType
metadata:
  labels:
    app.kubernetes.io/name: clustertype
    app.kubernetes.io/instance: clustertype-sample
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kalypso-scheduler
  name: clustertype-sample
spec:
  # TODO(user): Add fields here
